# Generated by Django 4.2.1 on 2023-07-14 08:37

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_topic_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='topic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic', validators=[app.models.check_for_a]),
        ),
    ]
