# Generated by Django 4.2.1 on 2023-07-14 08:41

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_topic_topic_name_alter_webpage_topic_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=100, validators=[app.models.check_for_a]),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='topic_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.topic'),
        ),
    ]
